/**
 * Predefined grocery item names for quick pick when adding products.
 * Owners still choose pack size and rate after selecting a name (or type any custom name).
 */
const RAW: readonly string[] = [
  "Atta (whole wheat)",
  "Besan (gram flour)",
  "Black chana",
  "Black pepper (whole)",
  "Boiled rice",
  "Brown sugar",
  "Butter",
  "Cardamom",
  "Chana dal",
  "Cheese block",
  "Chilli powder",
  "Cinnamon",
  "Cloves",
  "Coconut oil",
  "Cooking soda",
  "Corn flour",
  "Coriander powder",
  "Coriander seeds",
  "Cumin seeds",
  "Curd",
  "Custard powder",
  "Dettol / antiseptic",
  "Dish wash liquid",
  "Dry coconut",
  "Dry fish",
  "Eggs",
  "Fennel seeds",
  "Fenugreek seeds",
  "Flattened rice (poha)",
  "Floor cleaner",
  "Garam masala",
  "Ghee",
  "Green chana",
  "Green moong dal",
  "Groundnut oil",
  "Haldi (turmeric)",
  "Idli rice",
  "Jaggery",
  "Jeera (cumin) powder",
  "Kabuli chana",
  "Kasuri methi",
  "Ketchup",
  "Khoya / mawa",
  "Laundry detergent",
  "Lemon juice",
  "Lobia (black-eyed pea)",
  "Maida",
  "Masoor dal",
  "Mayonnaise",
  "Milk",
  "Mixed pickle",
  "Moong dal",
  "Mustard oil",
  "Mustard seeds",
  "Noodles",
  "Oats",
  "Palm oil",
  "Paneer",
  "Pasta",
  "Peanuts",
  "Poha",
  "Poppy seeds",
  "Ragi flour",
  "Raisins",
  "Raw rice",
  "Red chilli (whole)",
  "Refined flour",
  "Refined oil",
  "Refined sugar",
  "Rice",
  "Rock salt",
  "Sago (sabudana)",
  "Salt (iodized)",
  "Sambar powder",
  "Schezwan sauce",
  "Sea salt",
  "Semolina (sooji)",
  "Sesame oil",
  "Sesame seeds",
  "Soap bar",
  "Soya chunks",
  "Sugar",
  "Sunflower oil",
  "Suji",
  "Table salt",
  "Tamarind",
  "Tea dust",
  "Tea leaves",
  "Toilet cleaner",
  "Toor dal",
  "Tur dal",
  "Turmeric powder",
  "Urad dal",
  "Urad dal (split)",
  "Vermicelli (semiya)",
  "Vinegar",
  "Wheat flour",
  "White chana",
  "White urad",
  "Yeast",
];

export const PRESET_GROCERY_NAMES: readonly string[] = [...RAW].sort((a, b) =>
  a.localeCompare(b, undefined, { sensitivity: "base" }),
);
