/** TLD Groobey brand palette (logo: lime green, silver, black). */
export const GROOBEY_BRAND = {
  lime: "#9ACD32",
  limeDark: "#92c82e",
  silver: "#C0C0C0",
  silverDark: "#8A8A8A",
  black: "#0a0a0a",
  blackSoft: "#141414",
  white: "#ffffff",
  settlementBg: "#fff8f0",
  settlementBorder: "#ea580c",
} as const;

/** Full TLD Groobey mark for website UI only (login, dashboards, PWA icons). */
export const GROOBEY_WEB_LOGO_PATH = "/tld-groobey-web-logo.png";
export const GROOBEY_WEB_LOGO_FILE = "tld-groobey-web-logo.png";

/** Legacy bill pipeline source - not used in website UI. */
export const GROOBEY_LOGO_PATH = "/groobey-logo.png";
/** Hi-res logo for bills (generated by scripts/generate-bill-logo.mjs). */
export const GROOBEY_LOGO_BILL_PATH = "/groobey-logo-bill.png";
export const GROOBEY_LOGO_FILE = "groobey-logo.png";
export const GROOBEY_LOGO_BILL_FILE = "groobey-logo-bill.png";

/** Shared logo sizing for bills, PDF, and email (keep in sync). */
export const GROOBEY_LOGO_DISPLAY = {
  /** CSS / PDF display height (never upscale beyond bill asset). */
  billHeightPx: 72,
  billMaxWidthPx: 180,
  /** Generated asset height (4× display for print/zoom). */
  billAssetHeightPx: 288,
  billPlatePaddingPx: 12,
  /** Website logo display heights (portrait TLD + Groobey wordmark). */
  uiSm: 50,
  uiMd: 64,
  uiLg: 84,
  uiXl: 112,
} as const;

/** Table cell borders for print/email bills (matches base print styles). */
export const GROOBEY_BILL_BORDER = "#e5e7eb";

export function groobeyBillCellStyle(align: "left" | "right" = "left", extra = ""): string {
  const alignPart = align === "right" ? "text-align:right;" : "text-align:left;";
  return `padding:8px;border:1px solid ${GROOBEY_BILL_BORDER};${alignPart}${extra}`;
}

export function groobeyBillThStyle(align: "left" | "right" = "left"): string {
  const alignPart = align === "right" ? "text-align:right;" : "text-align:left;";
  return `padding:8px;border:1px solid ${GROOBEY_BRAND.limeDark};${alignPart}font-weight:700;`;
}

export const GROOBEY_APP_NAME = "TLD Groobey";
export const GROOBEY_PRODUCT_NAME = "Groobey Merchant Hub";

export type GroobeyBillThankYouKind = "customer" | "merchant";

/** Closing message on customer bills and bill emails. */
export const GROOBEY_CUSTOMER_THANK_YOU = {
  title: "Thank you!",
  message:
    "Thanks for shopping and booking with TLD Groobey. We appreciate your trust - please visit us again soon.",
} as const;

/** Closing on settlement / merchant bills (internal trade records). */
export const GROOBEY_MERCHANT_THANK_YOU = {
  title: "Thank you!",
  message:
    "Thanks for trading with TLD Groobey. We value this settlement - looking forward to our next order together.",
} as const;

export function groobeyBillThankYouCopy(kind: GroobeyBillThankYouKind) {
  return kind === "merchant" ? GROOBEY_MERCHANT_THANK_YOU : GROOBEY_CUSTOMER_THANK_YOU;
}

export function groobeyBillThankYouPlainText(kind: GroobeyBillThankYouKind): string {
  const copy = groobeyBillThankYouCopy(kind);
  return `${copy.title} ${copy.message}`;
}

/** @deprecated use groobeyBillThankYouPlainText("customer") */
export function groobeyCustomerThankYouPlainText(): string {
  return groobeyBillThankYouPlainText("customer");
}

/** Logo URL for bill preview / print (hi-res asset, same origin). */
export function groobeyBillLogoUrlForPrint(): string {
  if (typeof window !== "undefined" && window.location?.origin) {
    return `${window.location.origin}${GROOBEY_LOGO_BILL_PATH}`;
  }
  return GROOBEY_LOGO_BILL_PATH;
}

export function groobeyBillPrintHeaderHtml(options?: {
  logoSrc?: string;
  kind?: "customer" | "merchant";
}): string {
  const logo = options?.logoSrc?.trim() || groobeyBillLogoUrlForPrint();
  const tagline =
    options?.kind === "merchant" ?
      "Grocery trade · Internal settlement"
    : "";
  return `<header class="groobey-bill-header groobey-bill-header--light">
    <img src="${logo}" alt="${GROOBEY_APP_NAME}" class="groobey-bill-logo" decoding="sync" />
    ${tagline ? `<p class="groobey-bill-header-tagline">${tagline}</p>` : ""}
  </header>`;
}

export function groobeyBillPrintBaseStyles(): string {
  return `<style>
    body { color: ${GROOBEY_BRAND.blackSoft}; }
    h2, h3 { color: ${GROOBEY_BRAND.black}; }
    table thead tr { background: ${GROOBEY_BRAND.lime} !important; color: ${GROOBEY_BRAND.black} !important; }
    table thead th { border-color: ${GROOBEY_BRAND.limeDark} !important; font-weight: 700; }
    table tbody td { border-color: #e5e7eb !important; }
    hr { border: none; border-top: 2px solid ${GROOBEY_BRAND.lime}; opacity: 0.35; }
  </style>`;
}

/** Highlighted thank-you block before the bill footer. */
export function groobeyBillThankYouHtml(kind: GroobeyBillThankYouKind): string {
  const copy = groobeyBillThankYouCopy(kind);
  return `<div class="groobey-bill-thanks groobey-bill-thanks--${kind}" role="note">
    <p class="groobey-bill-thanks-title">${copy.title}</p>
    <p class="groobey-bill-thanks-body">${copy.message}</p>
  </div>`;
}

/** @deprecated use groobeyBillThankYouHtml("customer") */
export function groobeyCustomerBillThankYouHtml(): string {
  return groobeyBillThankYouHtml("customer");
}

/** Highlighted thank-you row for bill delivery emails (customer only). */
export function groobeyCustomerBillThankYouEmailHtml(): string {
  const copy = GROOBEY_CUSTOMER_THANK_YOU;
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 4px;">
    <tr>
      <td style="padding:18px 20px;border-radius:12px;text-align:center;background:linear-gradient(135deg,#f0fdf4 0%,#ecfccb 100%);border:2px solid ${GROOBEY_BRAND.lime};">
        <p style="margin:0 0 8px;font-size:20px;font-weight:800;color:${GROOBEY_BRAND.black};">${copy.title}</p>
        <p style="margin:0;font-size:15px;font-weight:600;line-height:1.55;color:#374151;">${copy.message}</p>
      </td>
    </tr>
  </table>`;
}

export function groobeyBillPrintFooterHtml(options?: { kind?: "customer" | "merchant" }): string {
  const productLine =
    options?.kind === "merchant" ?
      GROOBEY_PRODUCT_NAME
    : GROOBEY_APP_NAME;
  return `<footer class="groobey-bill-footer">
    <p class="groobey-bill-footer-brand">${GROOBEY_APP_NAME.toUpperCase()}</p>
    <p class="groobey-bill-footer-product">${productLine}</p>
  </footer>`;
}
