/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopOwnerRouteImport } from './routes/shop-owner'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlatformAdminRouteImport } from './routes/platform-admin'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamLoginRouteImport } from './routes/team/login'
import { Route as MySlugRouteImport } from './routes/my/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOwnerRoute = ShopOwnerRouteImport.update({
  id: '/shop-owner',
  path: '/shop-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminRoute = PlatformAdminRouteImport.update({
  id: '/platform-admin',
  path: '/platform-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamLoginRoute = TeamLoginRouteImport.update({
  id: '/team/login',
  path: '/team/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MySlugRoute = MySlugRouteImport.update({
  id: '/my/$slug',
  path: '/my/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/platform-admin': typeof PlatformAdminRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/shop-owner': typeof ShopOwnerRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/terms': typeof TermsRoute
  '/my/$slug': typeof MySlugRoute
  '/team/login': typeof TeamLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/platform-admin': typeof PlatformAdminRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/shop-owner': typeof ShopOwnerRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/terms': typeof TermsRoute
  '/my/$slug': typeof MySlugRoute
  '/team/login': typeof TeamLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/platform-admin': typeof PlatformAdminRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/shop-owner': typeof ShopOwnerRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/terms': typeof TermsRoute
  '/my/$slug': typeof MySlugRoute
  '/team/login': typeof TeamLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/orders'
    | '/platform-admin'
    | '/privacy'
    | '/profile'
    | '/shop'
    | '/shop-owner'
    | '/signup'
    | '/staff'
    | '/terms'
    | '/my/$slug'
    | '/team/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/orders'
    | '/platform-admin'
    | '/privacy'
    | '/profile'
    | '/shop'
    | '/shop-owner'
    | '/signup'
    | '/staff'
    | '/terms'
    | '/my/$slug'
    | '/team/login'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/orders'
    | '/platform-admin'
    | '/privacy'
    | '/profile'
    | '/shop'
    | '/shop-owner'
    | '/signup'
    | '/staff'
    | '/terms'
    | '/my/$slug'
    | '/team/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PlatformAdminRoute: typeof PlatformAdminRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ShopRoute: typeof ShopRoute
  ShopOwnerRoute: typeof ShopOwnerRoute
  SignupRoute: typeof SignupRoute
  StaffRoute: typeof StaffRoute
  TermsRoute: typeof TermsRoute
  MySlugRoute: typeof MySlugRoute
  TeamLoginRoute: typeof TeamLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-owner': {
      id: '/shop-owner'
      path: '/shop-owner'
      fullPath: '/shop-owner'
      preLoaderRoute: typeof ShopOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admin': {
      id: '/platform-admin'
      path: '/platform-admin'
      fullPath: '/platform-admin'
      preLoaderRoute: typeof PlatformAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/login': {
      id: '/team/login'
      path: '/team/login'
      fullPath: '/team/login'
      preLoaderRoute: typeof TeamLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/$slug': {
      id: '/my/$slug'
      path: '/my/$slug'
      fullPath: '/my/$slug'
      preLoaderRoute: typeof MySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PlatformAdminRoute: PlatformAdminRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ShopRoute: ShopRoute,
  ShopOwnerRoute: ShopOwnerRoute,
  SignupRoute: SignupRoute,
  StaffRoute: StaffRoute,
  TermsRoute: TermsRoute,
  MySlugRoute: MySlugRoute,
  TeamLoginRoute: TeamLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
