// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function browserLocalStorage(): Storage | undefined {
  try {
    if (typeof window === "undefined" || !window.localStorage) return undefined;
    return window.localStorage;
  } catch {
    return undefined;
  }
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      "Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or VITE_ prefixed versions) are set in your .env file.",
    );
  }

  const storage = browserLocalStorage();
  const canPersist = Boolean(storage);

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage,
      persistSession: canPersist,
      autoRefreshToken: canPersist,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;
let _clientHadPersist: boolean | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    const canPersist = Boolean(browserLocalStorage());
    // If the singleton was first created during SSR without storage, rebuild once localStorage exists.
    if (_supabase && canPersist && _clientHadPersist === false) {
      _supabase = undefined;
    }
    if (!_supabase) {
      _supabase = createSupabaseClient();
      _clientHadPersist = canPersist;
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});
